export type StepType =
  | 'single-select'
  | 'rating'
  | 'info-video'
  | 'info-image'
  | 'info-goal'
  | 'info-goal-2'
  | 'loading'
  | 'consent'
  | 'creating-plan'
  | 'trusted'
  | 'help-improve'
  | 'best-thing'
  | 'final-adjustment'

export interface QuizStep {
  id: string
  type: StepType
  theme: 'white' | 'dark'
  progress: number
  activeCheckmarks: number

  questionId?: number
  question?: string
  options?: string[]
  optionSubtexts?: string[]
  rateLabels?: [string, string]

  title?: string
  body?: string
  videoSrc?: string
  videoPoster?: string
  imageSrc?: string
  badgeType?: 'study' | 'survey'
  badgeText?: string
  sourceText?: string
  ctaText?: string

  prev?: string
  next?: string
}

export const QUIZ_STEPS: QuizStep[] = [
  {
    id: 'q0',
    type: 'single-select',
    theme: 'white',
    progress: 0,
    activeCheckmarks: 0,
    questionId: 0,
    question: 'Choose your main goal',
    options: ['Improve Erectile Function', 'Improve Ejaculation Control', 'Maximize Sexual Wellness'],
    optionSubtexts: ['', '', '(Improve both of the above)'],
    prev: '/',
    next: 'q201',
  },
  {
    id: 'q201',
    type: 'single-select',
    theme: 'white',
    progress: 3,
    activeCheckmarks: 0,
    questionId: 201,
    question: 'Which one best describes your problem?',
    options: ['Difficulty achieving erection', 'Difficulty maintaining erection', 'Both', "I don't want to answer"],
    prev: 'q0',
    next: 'q202',
  },
  {
    id: 'q202',
    type: 'single-select',
    theme: 'white',
    progress: 6,
    activeCheckmarks: 0,
    questionId: 202,
    question: 'How often do you experience problems with erection?',
    options: ['Never', 'Rarely', 'Often', 'All the time', "I don't want to answer"],
    prev: 'q201',
    next: 'q203',
  },
  {
    id: 'q203',
    type: 'single-select',
    theme: 'white',
    progress: 9,
    activeCheckmarks: 0,
    questionId: 203,
    question: 'How long have you been experiencing problems with erection?',
    options: ['Less than 1 year', 'From 1 to 5 years', 'From 5 to 10 years', 'More than 10 years', "I don't want to answer"],
    prev: 'q202',
    next: 'q204',
  },
  {
    id: 'q204',
    type: 'single-select',
    theme: 'white',
    progress: 12,
    activeCheckmarks: 0,
    questionId: 204,
    question: 'Can you have sex 2 times in a row?',
    options: ['Yes, but I must try hard', "No, I can't", "I don't want to answer"],
    prev: 'q203',
    next: 'ed-s1',
  },
  {
    id: 'ed-s1',
    type: 'info-video',
    theme: 'dark',
    progress: 16,
    activeCheckmarks: 1,
    title: 'Quality of Erection depends on the strength of the Pelvic Floor (PF) muscles',
    body: 'Stronger PF muscles help to fill & retain more blood in the male organ leading to harder and more lasting erection.',
    videoSrc: 'https://quiz.kegel-plan.com/video/video_ED_s1.mp4',
    ctaText: 'I got it',
    prev: 'q204',
    next: 'q205',
  },
  {
    id: 'q205',
    type: 'single-select',
    theme: 'white',
    progress: 19,
    activeCheckmarks: 1,
    questionId: 205,
    question: 'How often do you experience morning erections?',
    options: ['Never', 'Rarely', 'Often', 'All the time', "I don't want to answer"],
    prev: 'ed-s1',
    next: 'q206',
  },
  {
    id: 'q206',
    type: 'rating',
    theme: 'white',
    progress: 22,
    activeCheckmarks: 1,
    questionId: 206,
    question: 'How hard is your erection during masturbation?',
    rateLabels: ['Not hard', 'Very hard'],
    prev: 'q205',
    next: 'q207',
  },
  {
    id: 'q207',
    type: 'rating',
    theme: 'white',
    progress: 25,
    activeCheckmarks: 1,
    questionId: 207,
    question: 'How hard is your erection during sex?',
    rateLabels: ['Not hard', 'Very hard'],
    prev: 'q206',
    next: 'effective-exercises',
  },
  {
    id: 'effective-exercises',
    type: 'info-image',
    theme: 'dark',
    progress: 28,
    activeCheckmarks: 1,
    badgeType: 'study',
    badgeText: 'Study fact',
    title: '**Kegel Exercises** strengthen PF muscles, which effectively **enhances Erection**',
    imageSrc: 'https://quiz.kegel-plan.com/_vercel/image?url=%2Fimages%2Fen%2FEN_img_erection_84.webp&w=1536&q=100',
    sourceText: 'Source: Nuffield Somerset Hospital',
    ctaText: 'I got it',
    prev: 'q207',
    next: 'kegel-eff-2',
  },
  {
    id: 'kegel-eff-2',
    type: 'info-image',
    theme: 'dark',
    progress: 33,
    activeCheckmarks: 2,
    badgeType: 'survey',
    badgeText: 'User survey',
    title: '84% of men significantly improved erection by following the Kegel Plan',
    imageSrc: 'https://quiz.kegel-plan.com/_vercel/image?url=%2Fimages%2Fen%2FEN_img_erection_84.webp&w=1536&q=100',
    ctaText: 'I got it',
    prev: 'effective-exercises',
    next: 'q208',
  },
  {
    id: 'q208',
    type: 'rating',
    theme: 'white',
    progress: 37,
    activeCheckmarks: 2,
    questionId: 208,
    question: 'How satisfied are you with your sex life in the last 3 months?',
    rateLabels: ['Not satisfied', 'Very satisfied'],
    prev: 'kegel-eff-2',
    next: 'q209',
  },
  {
    id: 'q209',
    type: 'rating',
    theme: 'white',
    progress: 40,
    activeCheckmarks: 2,
    questionId: 209,
    question: 'How much do you worry about having problem with erection?',
    rateLabels: ["I don't worry", "I'm very worried"],
    prev: 'q208',
    next: 'q210',
  },
  {
    id: 'q210',
    type: 'rating',
    theme: 'white',
    progress: 43,
    activeCheckmarks: 2,
    questionId: 210,
    question: 'How much do erection problems affect the relationship with your partner?',
    rateLabels: ["They don't affect", 'They affect a lot'],
    prev: 'q209',
    next: 'q211',
  },
  {
    id: 'q211',
    type: 'single-select',
    theme: 'white',
    progress: 46,
    activeCheckmarks: 2,
    questionId: 211,
    question: 'Does your self-esteem suffer from problems with erection?',
    options: ['Yes, it does', "No, it doesn't", "I don't want to answer"],
    prev: 'q210',
    next: 'goal-page',
  },
  {
    id: 'goal-page',
    type: 'info-goal',
    theme: 'dark',
    progress: 55,
    activeCheckmarks: 2,
    title: 'Based on your personal goals you can',
    body: 'Improve **Sexual Wellness**',
    videoSrc: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_pp1.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_pp1_zaglushka.webp',
    ctaText: 'Continue',
    prev: 'q211',
    next: 'q212',
  },
  {
    id: 'q212',
    type: 'single-select',
    theme: 'white',
    progress: 58,
    activeCheckmarks: 2,
    questionId: 212,
    question: 'How long does your sex typically last?',
    options: ['Less than 2 minutes', '2-7 minutes', '7-15 minutes', '15 or more minutes'],
    prev: 'goal-page',
    next: 'q213',
  },
  {
    id: 'q213',
    type: 'single-select',
    theme: 'white',
    progress: 61,
    activeCheckmarks: 2,
    questionId: 213,
    question: "How often do you ejaculate earlier than you'd like?",
    options: ['Never', 'Rarely', 'Often', 'All the time', "I don't want to answer"],
    prev: 'q212',
    next: 'q214',
  },
  {
    id: 'q214',
    type: 'single-select',
    theme: 'white',
    progress: 63,
    activeCheckmarks: 2,
    questionId: 214,
    question: 'Do you want to improve ejaculation control?',
    options: ["Yes, I'd like to", "No, I don't want to"],
    prev: 'q213',
    next: 'q215',
  },
  {
    id: 'q215',
    type: 'rating',
    theme: 'white',
    progress: 65,
    activeCheckmarks: 2,
    questionId: 215,
    question: 'How would you rate your libido (sex drive) in the last 3 months?',
    rateLabels: ['Low', 'High'],
    prev: 'q214',
    next: 'q216',
  },
  {
    id: 'q216',
    type: 'single-select',
    theme: 'white',
    progress: 67,
    activeCheckmarks: 2,
    questionId: 216,
    question: 'Do you take any pills to improve sexual performance?',
    options: ['Yes, every time', 'I take them sometimes', "No, I don't", "I don't want to answer"],
    prev: 'q215',
    next: 'kegel-benefits',
  },
  {
    id: 'kegel-benefits',
    type: 'info-image',
    theme: 'dark',
    progress: 70,
    activeCheckmarks: 3,
    title: 'The Kegel Plan is better than pills',
    imageSrc: 'https://quiz.kegel-plan.com/_vercel/image?url=%2Fimages%2Fen%2FEN_img_pills_vs_kegel_Erection_Stamina.webp&w=1536&q=100',
    sourceText: 'Source: National Center for Biotechnology Info.',
    ctaText: 'I got it',
    prev: 'q216',
    next: 'q221',
  },
  {
    id: 'q221',
    type: 'single-select',
    theme: 'white',
    progress: 73,
    activeCheckmarks: 3,
    questionId: 221,
    question: 'How often do you drink alcohol?',
    options: ['Every day', 'Several times a week', 'Once a week', 'Once a month', "I don't drink at all"],
    prev: 'kegel-benefits',
    next: 'q222',
  },
  {
    id: 'q222',
    type: 'single-select',
    theme: 'white',
    progress: 76,
    activeCheckmarks: 3,
    questionId: 222,
    question: 'Do you smoke?',
    options: ['Yes, I do', "No, I don't", 'Sometimes'],
    prev: 'q221',
    next: 'q223',
  },
  {
    id: 'q223',
    type: 'rating',
    theme: 'white',
    progress: 82,
    activeCheckmarks: 3,
    questionId: 223,
    question: 'How healthy is your diet?',
    rateLabels: ['Unhealthy', 'Healthy'],
    prev: 'q222',
    next: 'goal-page-2',
  },
  {
    id: 'goal-page-2',
    type: 'info-goal-2',
    theme: 'white',
    progress: 85,
    activeCheckmarks: 3,
    title: 'Based on your personal goals you can',
    body: 'Improve **Sexual Wellness**',
    videoSrc: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_pp2.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_pp2_zaglushka.webp',
    ctaText: 'Continue',
    prev: 'q223',
    next: 'q225',
  },
  {
    id: 'q225',
    type: 'rating',
    theme: 'white',
    progress: 88,
    activeCheckmarks: 3,
    questionId: 225,
    question: "What's your level of physical activity?",
    rateLabels: ['Low', 'High'],
    prev: 'goal-page-2',
    next: 'q226',
  },
  {
    id: 'q226',
    type: 'rating',
    theme: 'white',
    progress: 92,
    activeCheckmarks: 3,
    questionId: 226,
    question: 'How would you rate your daily stress level?',
    rateLabels: ['Low', 'High'],
    prev: 'q225',
    next: 'health-loading',
  },
  {
    id: 'health-loading',
    type: 'loading',
    theme: 'white',
    progress: 95,
    activeCheckmarks: 4,
    title: 'Processing your health data...',
    prev: 'q226',
    next: 'health-consent',
  },
  {
    id: 'health-consent',
    type: 'consent',
    theme: 'white',
    progress: 95,
    activeCheckmarks: 4,
    prev: 'health-loading',
    next: 'creating-plan',
  },
  {
    id: 'creating-plan',
    type: 'creating-plan',
    theme: 'white',
    progress: 98,
    activeCheckmarks: 4,
    title: 'Analyzing your answers',
    prev: 'health-consent',
    next: 'trusted',
  },
  {
    id: 'trusted',
    type: 'trusted',
    theme: 'white',
    progress: 100,
    activeCheckmarks: 4,
    title: 'Congratulations on joining the millions of men prioritizing sexual wellness',
    videoSrc: 'https://quiz.kegel-plan.com/video/video_reviews_f2.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/video/posters/img_reviews_f2.webp',
    imageSrc: 'https://quiz.kegel-plan.com/_vercel/image?url=%2Fimages%2Fen%2FEN_img_4mil_men_ww.webp&w=1536&q=100',
    prev: 'creating-plan',
    next: 'help-improve',
  },
  {
    id: 'help-improve',
    type: 'help-improve',
    theme: 'white',
    progress: 100,
    activeCheckmarks: 4,
    title: 'Your Kegel plan will help you to improve:',
    prev: 'trusted',
    next: 'best-thing',
  },
  {
    id: 'best-thing',
    type: 'best-thing',
    theme: 'white',
    progress: 100,
    activeCheckmarks: 4,
    title: 'The best thing? It takes just 5 min a day',
    imageSrc: 'https://quiz.kegel-plan.com/_vercel/image?url=%2Fimages%2Fen%2FEN_img_5min_day.webp&w=1536&q=100',
    prev: 'help-improve',
    next: 'final-adjustment',
  },
  {
    id: 'final-adjustment',
    type: 'final-adjustment',
    theme: 'white',
    progress: 100,
    activeCheckmarks: 4,
    title: 'Final adjustment',
    videoSrc: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_final.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_final_zaglushka.webp',
    prev: 'best-thing',
    next: 'results',
  },
]

export const getStep = (id: string) => QUIZ_STEPS.find(s => s.id === id)
