export type StepType =
  | 'single-select'
  | 'rating'
  | 'info-video'
  | 'info-image'
  | 'info-goal'
  | 'info-goal-2'
  | 'loading'
  | 'consent'
  | 'creating-plan'
  | 'trusted'
  | 'help-improve'
  | 'best-thing'
  | 'final-adjustment'

export interface QuizStep {
  id: string
  type: StepType
  theme: 'white' | 'dark'
  progress: number
  activeCheckmarks: number

  // question
  questionId?: number
  question?: string
  options?: string[]
  optionSubtexts?: string[]
  rateLabels?: [string, string]

  // info
  title?: string
  body?: string
  videoSrc?: string
  videoPoster?: string
  imageSrc?: string
  badgeType?: 'study' | 'survey'
  badgeText?: string
  sourceText?: string
  ctaText?: string

  prev?: string
  next?: string
}

export const QUIZ_STEPS: QuizStep[] = [
  {
    id: 'q0',
    type: 'single-select',
    theme: 'white',
    progress: 0,
    activeCheckmarks: 0,
    questionId: 0,
    question: 'Choose your main goal',
    options: [
      'Improve Erectile Function',
      'Improve Ejaculation Control',
      'Maximize Sexual Wellness',
    ],
    optionSubtexts: ['', '', '(Improve both of the above)'],
    prev: '/',
    next: 'q201',
  },
  {
    id: 'q201',
    type: 'rating',
    theme: 'white',
    progress: 3.57,
    activeCheckmarks: 0,
    questionId: 201,
    question: 'How satisfied are you with your sexual wellness (erection quality & ejaculation control)?',
    rateLabels: ['Not satisfied', 'Very satisfied'],
    prev: 'q0',
    next: 'pe-s1',
  },
  {
    id: 'pe-s1',
    type: 'info-video',
    theme: 'dark',
    progress: 9.14,
    activeCheckmarks: 0,
    title: 'The ability to <span class="underline">control ejaculation</span> depends on the strength of the <span class="green">Pelvic Floor (PF) muscles</span>',
    body: 'Stronger PF muscles allow to control the ejaculatory reflex better and last longer.',
    videoSrc: 'https://quiz.kegel-plan.com/video/video_PE_s1.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/images/fallback-posters/video_PE_s1.webp',
    ctaText: 'Continue',
    prev: 'q201',
    next: 'ed-s1',
  },
  {
    id: 'ed-s1',
    type: 'info-video',
    theme: 'dark',
    progress: 13.71,
    activeCheckmarks: 0,
    title: '<span class="underline">Quality of Erection</span> also depends on the strength of the <span class="green">Pelvic Floor (PF) muscles</span>',
    body: 'Stronger PF muscles help to fill & retain more blood in the male organ leading to harder and more lasting erection.',
    videoSrc: 'https://quiz.kegel-plan.com/video/video_ED_s1.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/images/fallback-posters/video_ED_s1.webp',
    ctaText: 'I got it',
    prev: 'pe-s1',
    next: 'q204',
  },
  {
    id: 'q204',
    type: 'single-select',
    theme: 'white',
    progress: 17.28,
    activeCheckmarks: 1,
    questionId: 204,
    question: 'How long does your sex typically last?',
    options: [
      'Less than 2 minutes',
      '2-7 minutes',
      '7-15 minutes',
      '15 minutes or more',
    ],
    prev: 'ed-s1',
    next: 'q205',
  },
  {
    id: 'q205',
    type: 'single-select',
    theme: 'white',
    progress: 20.85,
    activeCheckmarks: 1,
    questionId: 205,
    question: 'How often do you ejaculate earlier than you\'d like?',
    options: ['Never', 'Rarely', 'Often', 'All the time', 'I don\'t want to answer'],
    prev: 'q204',
    next: 'q206',
  },
  {
    id: 'q206',
    type: 'single-select',
    theme: 'white',
    progress: 25.42,
    activeCheckmarks: 1,
    questionId: 206,
    question: 'How long do you want to last?',
    options: ['7-15 minutes', '15-20 minutes', '20-25 minutes', 'More than 25 minutes'],
    prev: 'q205',
    next: 'effective-exercises',
  },
  {
    id: 'effective-exercises',
    type: 'info-image',
    theme: 'dark',
    progress: 28.99,
    activeCheckmarks: 1,
    badgeType: 'study',
    badgeText: 'Study fact',
    title: '<span class="underline">Kegel Exercises</span> strengthen PF muscles, which significantly increases <span style="color:#53cc58">ejaculation control</span>',
    imageSrc: 'https://quiz.kegel-plan.com/_vercel/image?url=%2Fimages%2Fen%2FEN_img_sex_duration_7x.webp&w=1536&q=100',
    sourceText: 'Source: Sapienza University',
    ctaText: 'I got it',
    prev: 'q206',
    next: 'kegel-eff-1',
  },
  {
    id: 'kegel-eff-1',
    type: 'info-video',
    theme: 'dark',
    progress: 33.56,
    activeCheckmarks: 2,
    badgeType: 'survey',
    badgeText: 'User survey',
    title: '<span class="green">8 out of 10</span> men improved their ejaculation control by following <span class="underline">the Kegel Plan</span>',
    videoSrc: 'https://quiz.kegel-plan.com/video/video_8outof10.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/video/posters/img_8outof10.webp',
    ctaText: 'Continue',
    prev: 'effective-exercises',
    next: 'q209',
  },
  {
    id: 'q209',
    type: 'single-select',
    theme: 'white',
    progress: 36.13,
    activeCheckmarks: 2,
    questionId: 209,
    question: 'How would you describe your Erectile function?',
    options: [
      'Everything\'s great',
      'Mostly fine, but sometimes I have problems',
      'I often have problems',
      'I don\'t want to answer',
    ],
    prev: 'kegel-eff-1',
    next: 'q210',
  },
  {
    id: 'q210',
    type: 'single-select',
    theme: 'white',
    progress: 38.7,
    activeCheckmarks: 2,
    questionId: 210,
    question: 'How often do you experience difficulty getting an erection for sex?',
    options: ['Never', 'Rarely', 'Often', 'All the time', 'I don\'t want to answer'],
    prev: 'q209',
    next: 'q211',
  },
  {
    id: 'q211',
    type: 'single-select',
    theme: 'white',
    progress: 41.27,
    activeCheckmarks: 2,
    questionId: 211,
    question: 'How often do you experience difficulty maintaining an erection during sex?',
    options: ['Never', 'Rarely', 'Often', 'All the time', 'I don\'t want to answer'],
    prev: 'q210',
    next: 'q212',
  },
  {
    id: 'q212',
    type: 'single-select',
    theme: 'white',
    progress: 42.84,
    activeCheckmarks: 2,
    questionId: 212,
    question: 'Can you have sex 2 times in a row?',
    options: ['Yes, without any problems', 'Yes, but I must try hard', 'No, I can\'t', 'I don\'t want to answer'],
    prev: 'q211',
    next: 'kegel-eff-2',
  },
  {
    id: 'kegel-eff-2',
    type: 'info-image',
    theme: 'dark',
    progress: 45.41,
    activeCheckmarks: 2,
    badgeType: 'survey',
    badgeText: 'User survey',
    title: '<span class="green">84% of men</span> significantly improved erection by following <span class="underline">the Kegel Plan</span>',
    imageSrc: 'https://quiz.kegel-plan.com/_vercel/image?url=%2Fimages%2Fen%2FEN_img_erection_84.webp&w=1536&q=100',
    sourceText: 'Source: Kegel Plan user survey',
    ctaText: 'I got it',
    prev: 'q212',
    next: 'q214',
  },
  {
    id: 'q214',
    type: 'rating',
    theme: 'white',
    progress: 48.98,
    activeCheckmarks: 2,
    questionId: 214,
    question: 'How satisfied are you with your sex life in the last 3 months?',
    rateLabels: ['Not satisfied', 'Very satisfied'],
    prev: 'kegel-eff-2',
    next: 'q215',
  },
  {
    id: 'q215',
    type: 'single-select',
    theme: 'white',
    progress: 51.55,
    activeCheckmarks: 2,
    questionId: 215,
    question: 'Do you have a regular sexual partner?',
    options: ['Yes, I do', 'I have a partner, but not regular', 'No, I don\'t'],
    prev: 'q214',
    next: 'q216',
  },
  {
    id: 'q216',
    type: 'single-select',
    theme: 'white',
    progress: 54.12,
    activeCheckmarks: 2,
    questionId: 216,
    question: 'How often do you have sex?',
    options: ['Every day', 'Several times a week', 'Once a week', 'Once a month', 'I don\'t want to answer'],
    prev: 'q215',
    next: 'goal-page',
  },
  {
    id: 'goal-page',
    type: 'info-goal',
    theme: 'dark',
    progress: 58.69,
    activeCheckmarks: 2,
    title: 'Based on your personal goals you can',
    body: 'Improve **Sexual Wellness**',
    videoSrc: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_pp1.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_pp1_zaglushka.webp',
    ctaText: 'Continue',
    prev: 'q216',
    next: 'q218',
  },
  {
    id: 'q218',
    type: 'rating',
    theme: 'white',
    progress: 62.26,
    activeCheckmarks: 2,
    questionId: 218,
    question: 'How would you rate your libido (sex drive) in the last 3 months?',
    rateLabels: ['Low', 'High'],
    prev: 'goal-page',
    next: 'q219',
  },
  {
    id: 'q219',
    type: 'single-select',
    theme: 'white',
    progress: 65.83,
    activeCheckmarks: 2,
    questionId: 219,
    question: 'Do you take any pills to improve sexual performance?',
    options: ['Yes, every time', 'I take them sometimes', 'No, I don\'t'],
    prev: 'q218',
    next: 'kegel-benefits',
  },
  {
    id: 'kegel-benefits',
    type: 'info-image',
    theme: 'dark',
    progress: 68.4,
    activeCheckmarks: 3,
    title: 'The Kegel Plan is better than pills',
    imageSrc: 'https://quiz.kegel-plan.com/_vercel/image?url=%2Fimages%2Fen%2FEN_img_pills_vs_kegel_Erection_Stamina.webp&w=1536&q=100',
    sourceText: 'Source: National Center for Biotechnology Info.',
    ctaText: 'I got it',
    prev: 'q219',
    next: 'q221',
  },
  {
    id: 'q221',
    type: 'single-select',
    theme: 'white',
    progress: 74.97,
    activeCheckmarks: 3,
    questionId: 221,
    question: 'How often do you drink alcohol?',
    options: ['Every day', 'Several times a week', 'Once a week', 'Once a month', 'I don\'t drink at all'],
    prev: 'kegel-benefits',
    next: 'q222',
  },
  {
    id: 'q222',
    type: 'single-select',
    theme: 'white',
    progress: 78.54,
    activeCheckmarks: 3,
    questionId: 222,
    question: 'Do you smoke?',
    options: ['Yes, I do', 'No, I don\'t', 'Sometimes'],
    prev: 'q221',
    next: 'q223',
  },
  {
    id: 'q223',
    type: 'rating',
    theme: 'white',
    progress: 82.11,
    activeCheckmarks: 3,
    questionId: 223,
    question: 'How healthy is your diet?',
    rateLabels: ['Unhealthy', 'Healthy'],
    prev: 'q222',
    next: 'goal-page-2',
  },
  {
    id: 'goal-page-2',
    type: 'info-goal-2',
    theme: 'white',
    progress: 85.68,
    activeCheckmarks: 3,
    title: 'Based on your personal goals you can',
    body: 'Improve **Sexual Wellness**',
    videoSrc: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_pp2.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_pp2_zaglushka.webp',
    ctaText: 'Continue',
    prev: 'q223',
    next: 'q225',
  },
  {
    id: 'q225',
    type: 'rating',
    theme: 'white',
    progress: 88.25,
    activeCheckmarks: 3,
    questionId: 225,
    question: 'What\'s your level of physical activity?',
    rateLabels: ['Low', 'High'],
    prev: 'goal-page-2',
    next: 'q226',
  },
  {
    id: 'q226',
    type: 'rating',
    theme: 'white',
    progress: 91.82,
    activeCheckmarks: 3,
    questionId: 226,
    question: 'How would you rate your daily stress level?',
    rateLabels: ['Low', 'High'],
    prev: 'q225',
    next: 'health-loading',
  },
  {
    id: 'health-loading',
    type: 'loading',
    theme: 'white',
    progress: 95,
    activeCheckmarks: 4,
    title: 'Processing your health data...',
    prev: 'q226',
    next: 'health-consent',
  },
  {
    id: 'health-consent',
    type: 'consent',
    theme: 'white',
    progress: 95,
    activeCheckmarks: 4,
    prev: 'health-loading',
    next: 'creating-plan',
  },
  {
    id: 'creating-plan',
    type: 'creating-plan',
    theme: 'white',
    progress: 98,
    activeCheckmarks: 4,
    title: 'Analyzing your answers',
    prev: 'health-consent',
    next: 'trusted',
  },
  {
    id: 'trusted',
    type: 'trusted',
    theme: 'white',
    progress: 100,
    activeCheckmarks: 4,
    title: 'Congratulations on joining the millions of men prioritizing sexual wellness',
    videoSrc: 'https://quiz.kegel-plan.com/video/video_reviews_f2.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/video/posters/img_reviews_f2.webp',
    imageSrc: 'https://quiz.kegel-plan.com/_vercel/image?url=%2Fimages%2Fen%2FEN_img_4mil_men_ww.webp&w=1536&q=100',
    prev: 'creating-plan',
    next: 'help-improve',
  },
  {
    id: 'help-improve',
    type: 'help-improve',
    theme: 'white',
    progress: 100,
    activeCheckmarks: 4,
    title: 'Your Kegel plan will help you to improve:',
    prev: 'trusted',
    next: 'best-thing',
  },
  {
    id: 'best-thing',
    type: 'best-thing',
    theme: 'white',
    progress: 100,
    activeCheckmarks: 4,
    title: 'The best thing? It takes just 5 min a day',
    imageSrc: 'https://quiz.kegel-plan.com/_vercel/image?url=%2Fimages%2Fen%2FEN_img_5min_day.webp&w=1536&q=100',
    prev: 'help-improve',
    next: 'final-adjustment',
  },
  {
    id: 'final-adjustment',
    type: 'final-adjustment',
    theme: 'white',
    progress: 100,
    activeCheckmarks: 4,
    title: 'Final adjustment',
    body: 'Improve **Sexual Wellness**',
    videoSrc: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_final.mp4',
    videoPoster: 'https://quiz.kegel-plan.com/video/en/EN_video_graph_final_zaglushka.webp',
    prev: 'best-thing',
    next: 'results',
  },
]

export const getStep = (id: string) => QUIZ_STEPS.find(s => s.id === id)
